increment 9
AlLevykin/cutwell pull request #9
Opened 2022-05-27 01:54 UTC by AlLevykin

2022-07-06 12:33 UTC, blattaria7 commented on cmd/shortener/main.go
> +	"github.com/AlLevykin/cutwell/internal/utils"
Небольшой стилистический комментарий) В каждой компании в гошных репозиториях есть принятый стиль сортировки пакетов в импортах. Чаще всего это идет в таком порядке:
- stdlib 
- пакеты приложения
- внешние зависимости

Это можно получить путём установки и настройки в IDE комбинации https://golangci-lint.run/usage/install/ и goimports
Или же добавлением конфигураций с линтерами, которые это проверяют)

2022-07-06 12:54 UTC, blattaria7 requested changes
Задание выполнено хорошо, но нужно внести небольшие стилистические доработки и убедиться что с ними все работает)

Также рекомендую попробовать добавить к коду конфигурационный файл с линтерами https://golangci-lint.run/. Они автоматизируют поиск такого рода ошибок и помогают находить даже логические ошибки )  (это не обязательно, просто рекомендация)

2022-07-06 12:54 UTC, blattaria7 commented on cmd/shortener/main.go
> +	"github.com/AlLevykin/cutwell/internal/utils"
Небольшой стилистический комментарий. В каждой компании в гошных репозиториях есть принятый стиль сортировки пакетов в импортах. Чаще всего делают так:
- stdlib
- пакеты приложения
- внешние зависимости

Это можно получить путём установки и настройки в IDE комбинации https://golangci-lint.run/usage/install/ и goimports или же добавлением конфигурационного файла с линтерами (линтер gofumpt), который будет это проверять)

2022-07-06 12:54 UTC, blattaria7 commented on internal/app/pg-store/store.go
> +	defer tx.Rollback()
метод tx.Rollback() возвращает ошибку, ее необходимо обработать

2022-07-06 12:54 UTC, blattaria7 commented on cmd/shortener/main.go
>  	env.Parse(&cfg)
этот метод точно возвращает ошибку. ее нужно обработать и залоггировать результат

2022-07-06 12:54 UTC, blattaria7 commented on internal/api/handler/handler.go
> +	w.WriteHeader(status.(int))
при приведении к типу необходимо делать проверку на то, что все успешно привелось)

```go
statusInt, ok := status.(int)
	if !ok {
		// ...
	}
w.WriteHeader(statusInt)
```

2022-07-06 12:54 UTC, blattaria7 commented on cmd/shortener/main.go
> +	if len(cfg.DBDSN) == 0 {
здесь правильнее будет проверить то, что строка не пустая(`if cfg.DBDSN != "" `), а не отталкиваться от ее размера)

2022-07-06 12:54 UTC, blattaria7 commented on internal/api/handler/handler.go
> +	Create(ctx context.Context, lnk string, u string) (string, error)
переменную `u` лучше назвать более полно (для повышения читаемости)

2022-07-06 12:54 UTC, blattaria7 commented on internal/api/handler/handler.go
> +	Batch(ctx context.Context, b []BatchItem, u string) ([]ResultItem, error)
тут тоже самое с переменной `u` и заодно с `b`)

2022-07-06 19:24 UTC, AlLevykin commented on cmd/shortener/main.go
> +	"github.com/AlLevykin/cutwell/internal/utils"
Импорт сортируется автоматически IDE Goland.

2022-07-07 16:00 UTC, blacknoire7 approved these changes
Все прекрасно, ставлю аппрув)

2022-07-14 01:46 UTC, merged